server:
    port: 8868
    shutdown: graceful

spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/DemoDB
        username: root
        password:
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MariaDBDialect
        show-sql: false
        hibernate:
            ddl-auto: update
    lifecycle:
        timeout-per-shutdown-phase: 130s